// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.ZanderProvider.Runtime")>]
[<assembly: AssemblyProductAttribute("FSharp.ZanderProvider")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing FSharp.ZanderProvider.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.ZanderProvider.Runtime"
    let [<Literal>] AssemblyProduct = "FSharp.ZanderProvider"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing FSharp.ZanderProvider."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
