// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Zander")>]
[<assembly: AssemblyProductAttribute("Zander")>]
[<assembly: AssemblyDescriptionAttribute("Small library to extract information out of matrix blocks (read matrix data from excel, csv)")>]
[<assembly: AssemblyVersionAttribute("3.0.0")>]
[<assembly: AssemblyFileVersionAttribute("3.0.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Zander"
    let [<Literal>] AssemblyProduct = "Zander"
    let [<Literal>] AssemblyDescription = "Small library to extract information out of matrix blocks (read matrix data from excel, csv)"
    let [<Literal>] AssemblyVersion = "3.0.0"
    let [<Literal>] AssemblyFileVersion = "3.0.0"
    let [<Literal>] AssemblyConfiguration = "Release"
